import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Legal & Disclaimer — Open Common Ground',
  description: 'Disclaimer, data sources, and privacy information for Open Common Ground.',
}

export default function LegalPage() {
  return (
    <div className="max-w-2xl space-y-8">
      <div>
        <h1 className="text-2xl font-bold mb-1">Legal &amp; Disclaimer</h1>
        <p className="text-sm text-muted-foreground">Last updated: May 2026</p>
      </div>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">AI-Generated Content</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Summaries, impact assessments, and political perspectives on this site are generated by artificial intelligence.
          They are provided for informational purposes only and may contain errors, omissions, or inaccuracies.
          Nothing on this site constitutes legal advice, political advice, or an endorsement of any position or candidate.
          Always read the source legislation and consult qualified professionals before acting on any information presented here.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">Data Sources</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Bill data is sourced from{' '}
          <a
            href="https://phila.legistar.com"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-foreground transition-colors"
          >
            Philadelphia Legistar
          </a>
          , the official public record system maintained by Philadelphia City Council.
          Council member information and vote records are also derived from Legistar.
          We make reasonable efforts to keep data current but do not guarantee completeness or timeliness.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">No Government Affiliation</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Open Common Ground is an independent civic technology project operated by Caines Ventures LLC.
          It is not affiliated with, endorsed by, or operated by Philadelphia City Council, the City of Philadelphia,
          or any government agency or official.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">Privacy</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          When you sign in with Google, we store your name, email address, and profile picture to power your account.
          We do not sell your personal data to third parties. We use{' '}
          <a
            href="https://posthog.com"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-foreground transition-colors"
          >
            PostHog
          </a>{' '}
          for anonymous product analytics to understand how the site is used and improve it.
          You can opt out of analytics by enabling Do Not Track in your browser.
        </p>
        <p className="text-sm text-muted-foreground leading-relaxed">
          To request deletion of your account and associated data, email{' '}
          <a href="mailto:hello@opencommonground.com" className="underline hover:text-foreground transition-colors">
            hello@opencommonground.com
          </a>{' '}
          with the subject line &ldquo;Delete my account.&rdquo; We will process your request within 30 days.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">Limitation of Liability</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Open Common Ground is provided &ldquo;as is&rdquo; without warranty of any kind. We are not liable for any damages
          arising from your use of this site, reliance on AI-generated content, or inaccuracies in the underlying data.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">Contact</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Questions or concerns? Email{' '}
          <a href="mailto:hello@opencommonground.com" className="underline hover:text-foreground transition-colors">
            hello@opencommonground.com
          </a>
          .
        </p>
      </section>

      <div className="pt-4 border-t">
        <Link href="/" className="text-sm text-primary hover:underline">← Back to home</Link>
      </div>
    </div>
  )
}
