"""add_user_digest_preferences

Revision ID: 56fd11557c6c
Revises: 55a36372d8b9
Create Date: 2026-04-06 12:24:33.996612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56fd11557c6c'
down_revision: Union[str, None] = '55a36372d8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # SQLite requires nullable=True for ADD COLUMN; defaults are applied via UPDATE
    op.add_column('users', sa.Column('digest_frequency', sa.String(), nullable=True))
    op.add_column('users', sa.Column('digest_min_impact', sa.String(), nullable=True))
    op.execute("UPDATE users SET digest_frequency = 'weekly' WHERE digest_frequency IS NULL")
    op.execute("UPDATE users SET digest_min_impact = 'low' WHERE digest_min_impact IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'digest_min_impact')
    op.drop_column('users', 'digest_frequency')
    # ### end Alembic commands ###
