"""perspectives_councilmembers_tracking_donations_cache

Revision ID: a10d347e2376
Revises: f1b8d4e03c92
Create Date: 2026-03-28 21:29:14.409933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10d347e2376'
down_revision: Union[str, None] = 'f1b8d4e03c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregated_data_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'key', name='uq_cache_source_key')
    )
    op.create_table('councilmembers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('bills_sponsored', sa.Integer(), nullable=True),
    sa.Column('bills_passed', sa.Integer(), nullable=True),
    sa.Column('legistar_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legistar_id')
    )
    op.create_table('donations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('donor_email', sa.String(), nullable=True),
    sa.Column('donation_type', sa.String(), nullable=True),
    sa.Column('stripe_payment_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_perspectives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bill_id', sa.String(), nullable=False),
    sa.Column('perspective_type', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('key_arguments', sa.Text(), nullable=True),
    sa.Column('concerns', sa.Text(), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('ai_provider', sa.String(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['legislation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id', 'perspective_type', name='uq_perspective_per_bill')
    )
    op.create_index(op.f('ix_bill_perspectives_bill_id'), 'bill_perspectives', ['bill_id'], unique=False)
    op.create_table('bill_tracking',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('bill_id', sa.String(), nullable=False),
    sa.Column('tracked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['legislation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'bill_id', name='uq_tracking_per_user')
    )
    op.create_index(op.f('ix_bill_tracking_bill_id'), 'bill_tracking', ['bill_id'], unique=False)
    op.create_index(op.f('ix_bill_tracking_user_id'), 'bill_tracking', ['user_id'], unique=False)
    op.add_column('legislation', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('legislation', sa.Column('impact_score', sa.Integer(), nullable=True))
    op.add_column('legislation', sa.Column('impact_level', sa.String(), nullable=True))
    op.add_column('legislation', sa.Column('bill_type', sa.String(), nullable=True))
    op.add_column('legislation', sa.Column('supplementary_data', sa.Text(), nullable=True))
    op.add_column('legislation', sa.Column('news_links', sa.Text(), nullable=True))
    op.add_column('legislation', sa.Column('times_tracked', sa.Integer(), nullable=True))
    op.add_column('legislation', sa.Column('analyzed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legislation', 'analyzed_at')
    op.drop_column('legislation', 'times_tracked')
    op.drop_column('legislation', 'news_links')
    op.drop_column('legislation', 'supplementary_data')
    op.drop_column('legislation', 'bill_type')
    op.drop_column('legislation', 'impact_level')
    op.drop_column('legislation', 'impact_score')
    op.drop_column('legislation', 'summary')
    op.drop_index(op.f('ix_bill_tracking_user_id'), table_name='bill_tracking')
    op.drop_index(op.f('ix_bill_tracking_bill_id'), table_name='bill_tracking')
    op.drop_table('bill_tracking')
    op.drop_index(op.f('ix_bill_perspectives_bill_id'), table_name='bill_perspectives')
    op.drop_table('bill_perspectives')
    op.drop_table('donations')
    op.drop_table('councilmembers')
    op.drop_table('aggregated_data_cache')
    # ### end Alembic commands ###
