"""initial schema

Revision ID: c5b1a7160033
Revises: 
Create Date: 2026-03-16 18:53:59.257135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b1a7160033'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legislation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('bill_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('sponsor', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('introduced_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('external_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_developer', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('persona', sa.String(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('expertise_areas', sa.String(), nullable=True),
    sa.Column('agent_type', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('api_url', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('avatar_id', sa.String(), nullable=True),
    sa.Column('voice_id', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_agents_owner_user_id'), 'agents', ['owner_user_id'], unique=False)
    op.create_table('debates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('legislation_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=True),
    sa.Column('max_turns', sa.Integer(), nullable=True),
    sa.Column('current_turn_agent_id', sa.String(), nullable=True),
    sa.Column('research_enabled', sa.Boolean(), nullable=True),
    sa.Column('research_data', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_turn_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debate_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('debate_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('argument', sa.Text(), nullable=False),
    sa.Column('citations', sa.Text(), nullable=True),
    sa.Column('reasoning_chain', sa.Text(), nullable=True),
    sa.Column('research_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debate_participants',
    sa.Column('debate_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], )
    )
    op.create_table('debate_videos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('debate_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_video_id', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debate_videos_debate_id'), 'debate_videos', ['debate_id'], unique=False)
    op.create_table('legislation_votes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('legislation_id', sa.String(), nullable=False),
    sa.Column('debate_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('vote', sa.String(), nullable=False),
    sa.Column('voter_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legislation_id', 'voter_token', name='uq_vote_per_voter')
    )
    op.create_index(op.f('ix_legislation_votes_legislation_id'), 'legislation_votes', ['legislation_id'], unique=False)
    op.create_index(op.f('ix_legislation_votes_user_id'), 'legislation_votes', ['user_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('rater_agent_id', sa.String(), nullable=False),
    sa.Column('persuasiveness_score', sa.Float(), nullable=True),
    sa.Column('logical_soundness_score', sa.Float(), nullable=True),
    sa.Column('factual_accuracy_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['debate_messages.id'], ),
    sa.ForeignKeyConstraint(['rater_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.drop_index(op.f('ix_legislation_votes_user_id'), table_name='legislation_votes')
    op.drop_index(op.f('ix_legislation_votes_legislation_id'), table_name='legislation_votes')
    op.drop_table('legislation_votes')
    op.drop_index(op.f('ix_debate_videos_debate_id'), table_name='debate_videos')
    op.drop_table('debate_videos')
    op.drop_table('debate_participants')
    op.drop_table('debate_messages')
    op.drop_table('debates')
    op.drop_index(op.f('ix_agents_owner_user_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('legislation')
    # ### end Alembic commands ###
