"""drop_debate_engine_tables

Revision ID: e861ec7b1a2a
Revises: 0a4c0a92999d
Create Date: 2026-04-09 18:23:15.036891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e861ec7b1a2a'
down_revision: Union[str, None] = '0a4c0a92999d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop debate engine tables (safe — uses IF EXISTS for DBs that never had them)
    op.execute('DROP TABLE IF EXISTS debate_participants')
    op.execute('DROP TABLE IF EXISTS debate_videos')
    op.execute('DROP TABLE IF EXISTS ratings')
    op.execute('DROP TABLE IF EXISTS debate_messages')
    op.execute('DROP TABLE IF EXISTS debates')
    op.execute('DROP TABLE IF EXISTS agents')

    # Drop debate_id column from legislation_votes via copy-and-move (SQLite can't drop FK columns)
    conn = op.get_bind()
    cols = [row[1] for row in conn.execute(sa.text("PRAGMA table_info(legislation_votes)")).fetchall()]
    if 'debate_id' in cols:
        conn.execute(sa.text("""
            CREATE TABLE legislation_votes_new (
                id VARCHAR NOT NULL,
                legislation_id VARCHAR NOT NULL,
                user_id VARCHAR,
                vote VARCHAR NOT NULL,
                voter_token VARCHAR NOT NULL,
                created_at DATETIME,
                updated_at DATETIME,
                PRIMARY KEY (id),
                CONSTRAINT uq_vote_per_voter UNIQUE (legislation_id, voter_token),
                FOREIGN KEY(legislation_id) REFERENCES legislation (id),
                FOREIGN KEY(user_id) REFERENCES users (id)
            )
        """))
        conn.execute(sa.text("""
            INSERT INTO legislation_votes_new
                (id, legislation_id, user_id, vote, voter_token, created_at, updated_at)
            SELECT id, legislation_id, user_id, vote, voter_token, created_at, updated_at
            FROM legislation_votes
        """))
        conn.execute(sa.text("DROP TABLE legislation_votes"))
        conn.execute(sa.text("ALTER TABLE legislation_votes_new RENAME TO legislation_votes"))
        conn.execute(sa.text("CREATE INDEX ix_legislation_votes_legislation_id ON legislation_votes (legislation_id)"))
        conn.execute(sa.text("CREATE INDEX ix_legislation_votes_user_id ON legislation_votes (user_id)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'digest_min_impact',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'digest_frequency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('legislation_votes', sa.Column('debate_id', sa.VARCHAR(), nullable=True))
    op.create_foreign_key(None, 'legislation_votes', 'debates', ['debate_id'], ['id'])
    op.create_table('agents',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('persona', sa.VARCHAR(), nullable=True),
    sa.Column('system_prompt', sa.TEXT(), nullable=True),
    sa.Column('expertise_areas', sa.VARCHAR(), nullable=True),
    sa.Column('agent_type', sa.VARCHAR(), nullable=True),
    sa.Column('model_name', sa.VARCHAR(), nullable=True),
    sa.Column('api_url', sa.VARCHAR(), nullable=True),
    sa.Column('api_key', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('avatar_id', sa.VARCHAR(), nullable=True),
    sa.Column('voice_id', sa.VARCHAR(), nullable=True),
    sa.Column('owner_user_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_agents_owner_user_id', 'agents', ['owner_user_id'], unique=False)
    op.create_table('debate_messages',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('debate_id', sa.VARCHAR(), nullable=False),
    sa.Column('agent_id', sa.VARCHAR(), nullable=False),
    sa.Column('turn_number', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.VARCHAR(), nullable=True),
    sa.Column('argument', sa.TEXT(), nullable=False),
    sa.Column('citations', sa.TEXT(), nullable=True),
    sa.Column('reasoning_chain', sa.TEXT(), nullable=True),
    sa.Column('research_data', sa.TEXT(), nullable=True),
    sa.Column('argument_variants', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('message_id', sa.VARCHAR(), nullable=False),
    sa.Column('rater_agent_id', sa.VARCHAR(), nullable=False),
    sa.Column('persuasiveness_score', sa.FLOAT(), nullable=True),
    sa.Column('logical_soundness_score', sa.FLOAT(), nullable=True),
    sa.Column('factual_accuracy_score', sa.FLOAT(), nullable=True),
    sa.Column('relevance_score', sa.FLOAT(), nullable=True),
    sa.Column('overall_score', sa.FLOAT(), nullable=True),
    sa.Column('reasoning', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['debate_messages.id'], ),
    sa.ForeignKeyConstraint(['rater_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debate_videos',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('debate_id', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('provider_video_id', sa.VARCHAR(), nullable=True),
    sa.Column('video_url', sa.VARCHAR(), nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(), nullable=True),
    sa.Column('duration_seconds', sa.FLOAT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('celery_task_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_debate_videos_debate_id', 'debate_videos', ['debate_id'], unique=False)
    op.create_table('debates',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('legislation_id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('topic', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('turn_count', sa.INTEGER(), nullable=True),
    sa.Column('max_turns', sa.INTEGER(), nullable=True),
    sa.Column('current_turn_agent_id', sa.VARCHAR(), nullable=True),
    sa.Column('research_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('research_data', sa.TEXT(), nullable=True),
    sa.Column('participant_settings', sa.TEXT(), nullable=True),
    sa.Column('created_by_user_id', sa.VARCHAR(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.Column('share_count', sa.INTEGER(), nullable=True),
    sa.Column('view_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_turn_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_debates_created_by_user_id', 'debates', ['created_by_user_id'], unique=False)
    op.create_table('debate_participants',
    sa.Column('debate_id', sa.VARCHAR(), nullable=True),
    sa.Column('agent_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], )
    )
    # ### end Alembic commands ###
