"""councilmember_extended_fields

Revision ID: eb99427523d3
Revises: a10d347e2376
Create Date: 2026-03-29 08:20:14.047971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb99427523d3'
down_revision: Union[str, None] = 'a10d347e2376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('councilmembers', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('councilmembers', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('councilmembers', sa.Column('profile_url', sa.String(), nullable=True))
    op.add_column('councilmembers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('councilmembers', 'updated_at')
    op.drop_column('councilmembers', 'profile_url')
    op.drop_column('councilmembers', 'bio')
    op.drop_column('councilmembers', 'photo_url')
    # ### end Alembic commands ###
