"""add_bill_vote_records

Revision ID: f2df069b6946
Revises: 56fd11557c6c
Create Date: 2026-04-06 17:53:18.442658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2df069b6946'
down_revision: Union[str, None] = '56fd11557c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_vote_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('legislation_id', sa.String(), nullable=False),
    sa.Column('councilmember_id', sa.String(), nullable=True),
    sa.Column('voter_name', sa.String(), nullable=False),
    sa.Column('vote', sa.String(), nullable=False),
    sa.Column('action_date', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['councilmember_id'], ['councilmembers.id'], ),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legislation_id', 'voter_name', name='uq_vote_record_per_member_bill')
    )
    op.create_index(op.f('ix_bill_vote_records_councilmember_id'), 'bill_vote_records', ['councilmember_id'], unique=False)
    op.create_index(op.f('ix_bill_vote_records_legislation_id'), 'bill_vote_records', ['legislation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_vote_records_legislation_id'), table_name='bill_vote_records')
    op.drop_index(op.f('ix_bill_vote_records_councilmember_id'), table_name='bill_vote_records')
    op.drop_table('bill_vote_records')
    # ### end Alembic commands ###
