"""add_plain_title_to_legislation

Revision ID: f84f819166f4
Revises: eb99427523d3
Create Date: 2026-03-29 09:45:34.305460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84f819166f4'
down_revision: Union[str, None] = 'eb99427523d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legislation', sa.Column('plain_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legislation', 'plain_title')
    # ### end Alembic commands ###
